# Generated by Django 5.2.8 on 2025-11-16 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='porte',
            field=models.CharField(blank=True, choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AnimalFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.animal')),
            ],
            options={
                'verbose_name': 'Foto do Animal',
                'verbose_name_plural': 'Fotos do Animal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnimalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.animal')),
            ],
            options={
                'verbose_name': 'Vídeo do Animal',
                'verbose_name_plural': 'Vídeos do Animal',
                'ordering': ['id'],
            },
        ),
    ]
