# Generated by Django 5.2.8 on 2025-11-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_cidade_animal_estado_animal_imagem_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfoto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animais/fotos/'),
        ),
        migrations.AlterField(
            model_name='animalfoto',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
