# Generated by Django 5.2.8 on 2025-11-19 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animalfoto_imagem_alter_animalfoto_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='moderador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_moderadas', to=settings.AUTH_USER_MODEL, verbose_name='Moderador'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='observacoes_moderador',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Moderador'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('em_andamento', 'Em Andamento'), ('resolvida', 'Resolvida'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='core.usuario'),
        ),
    ]
