# Generated by Django 5.2.8 on 2025-11-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_denuncia_moderador_denuncia_observacoes_moderador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='denuncias/videos/', verbose_name='Vídeo'),
        ),
    ]
