# Generated by Django 5.2.8 on 2025-11-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_denuncia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='denuncias/videos/', verbose_name='Vídeo Principal'),
        ),
        migrations.CreateModel(
            name='DenunciaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='denuncias/imagens/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='core.denuncia')),
            ],
            options={
                'verbose_name': 'Imagem da Denúncia',
                'verbose_name_plural': 'Imagens da Denúncia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='denuncias/videos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_adicionais', to='core.denuncia')),
            ],
            options={
                'verbose_name': 'Vídeo da Denúncia',
                'verbose_name_plural': 'Vídeos da Denúncia',
                'ordering': ['id'],
            },
        ),
    ]
