# Generated by Django 5.2.8 on 2025-11-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_denuncia_imagem_alter_denuncia_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('maus_tratos', 'Maus-tratos'), ('abandono', 'Abandono'), ('acumulacao', 'Acumulação de Animais'), ('animal_perdido', 'Animal Perdido'), ('animal_ferido', 'Animal Ferido'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
    ]
