# Generated by Django 5.2.8 on 2025-11-20 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_denuncia_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Denúncia Criada'), ('status', 'Mudança de Status'), ('comentario', 'Comentário Adicionado'), ('atribuicao', 'Moderador Atribuído')], max_length=20, verbose_name='Tipo de Ação')),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status Novo')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.denuncia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico da Denúncia',
                'verbose_name_plural': 'Histórico das Denúncias',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
