# Generated by Django 5.2.8 on 2025-11-20 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_denunciahistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalParaAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Animal')),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno (até 10kg)'), ('medio', 'Médio (10kg a 25kg)'), ('grande', 'Grande (acima de 25kg)')], max_length=10, verbose_name='Porte')),
                ('descricao', models.TextField(help_text='Descreva o temperamento, cuidados especiais, etc.', verbose_name='Descrição do Animal')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco_completo', models.CharField(help_text='Será compartilhado apenas após aprovação da adoção', max_length=255, verbose_name='Endereço Completo')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone para Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail para Contato')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='adocao/pendentes/', verbose_name='Foto Principal')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('adotado', 'Adotado')], default='pendente', max_length=20, verbose_name='Status')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('moderador_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Moderador que Aprovou')),
                ('usuario_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais_para_adocao', to='core.usuario', verbose_name='Usuário que cadastrou')),
            ],
            options={
                'verbose_name': 'Animal para Adoção',
                'verbose_name_plural': 'Animais para Adoção',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adocao_aprovada', 'Adoção Aprovada'), ('adocao_rejeitada', 'Adoção Rejeitada'), ('animal_aprovado', 'Animal Aprovado para Doação'), ('animal_rejeitado', 'Animal Rejeitado'), ('interesse_adocao', 'Novo Interesse em Adoção'), ('denuncia', 'Denúncia')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link de Ação')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('contato_telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de Contato')),
                ('contato_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('contato_endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, help_text='Conte um pouco sobre você e por que quer adotar', null=True, verbose_name='Mensagem do Interessado')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Aprovação'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('notificado_doador', models.BooleanField(default=False, verbose_name='Doador Notificado')),
                ('notificado_interessado', models.BooleanField(default=False, verbose_name='Interessado Notificado')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.animalparaadocao', verbose_name='Animal')),
                ('moderador_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Moderador que Aprovou')),
                ('usuario_interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_adocao', to='core.usuario', verbose_name='Interessado em Adotar')),
            ],
            options={
                'verbose_name': 'Solicitação de Adoção',
                'verbose_name_plural': 'Solicitações de Adoção',
                'ordering': ['-data_solicitacao'],
                'unique_together': {('animal', 'usuario_interessado')},
            },
        ),
    ]
