# Generated by Django 5.2.8 on 2025-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_animalparaadocao_notificacao_solicitacaoadocao"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalparaadocao",
            name="caracteristicas_especiais",
            field=models.TextField(
                blank=True, null=True, verbose_name="Características Especiais"
            ),
        ),
        migrations.AddField(
            model_name="animalparaadocao",
            name="cor",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cor"
            ),
        ),
        migrations.AddField(
            model_name="animalparaadocao",
            name="historico_saude",
            field=models.TextField(
                blank=True,
                help_text="Vacinas, castração, doenças, etc.",
                null=True,
                verbose_name="Histórico de Saúde",
            ),
        ),
        migrations.AddField(
            model_name="animalparaadocao",
            name="idade",
            field=models.CharField(
                blank=True,
                help_text="Ex: 2 anos, 6 meses, filhote",
                max_length=50,
                null=True,
                verbose_name="Idade",
            ),
        ),
        migrations.AddField(
            model_name="animalparaadocao",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Macho"), ("F", "Fêmea"), ("N", "Não informado")],
                default="N",
                max_length=1,
                verbose_name="Sexo",
            ),
        ),
        migrations.AddField(
            model_name="animalparaadocao",
            name="temperamento",
            field=models.TextField(
                blank=True,
                help_text="Ex: dócil, brincalhão, calmo",
                null=True,
                verbose_name="Temperamento",
            ),
        ),
    ]
