# Generated by Django 5.2.8 on 2025-11-21 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_animalparaadocao_caracteristicas_especiais_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_respondidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contato',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_atendimento', 'Em Atendimento'), ('respondido', 'Respondido'), ('resolvido', 'Resolvido')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='contato',
            name='usuario_notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('adocao_aprovada', 'Adoção Aprovada'), ('adocao_rejeitada', 'Adoção Rejeitada'), ('animal_aprovado', 'Animal Aprovado para Doação'), ('animal_rejeitado', 'Animal Rejeitado'), ('interesse_adocao', 'Novo Interesse em Adoção'), ('denuncia', 'Denúncia'), ('contato_recebido', 'Contato Recebido'), ('contato_respondido', 'Contato Respondido')], max_length=30, verbose_name='Tipo'),
        ),
    ]
