# Generated by Django 5.2.8 on 2025-11-21 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contato_data_leitura_contato_data_resposta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('raca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor/Pelagem')),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, verbose_name='Porte')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('N', 'Não informado')], default='N', max_length=1, verbose_name='Sexo')),
                ('idade_aproximada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idade Aproximada')),
                ('caracteristicas_distintivas', models.TextField(help_text='Manchas, cicatrizes, coleira, etc.', verbose_name='Características Distintivas')),
                ('descricao', models.TextField(help_text='Conte o que aconteceu e onde o pet foi visto pela última vez', verbose_name='Descrição Detalhada')),
                ('data_perda', models.DateField(verbose_name='Data da Perda')),
                ('hora_perda', models.TimeField(blank=True, null=True, verbose_name='Hora Aproximada')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Aproximado')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('telefone_contato', models.CharField(max_length=15, verbose_name='Telefone para Contato')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail para Contato')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp')),
                ('oferece_recompensa', models.BooleanField(default=False, verbose_name='Oferece Recompensa')),
                ('valor_recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Recompensa')),
                ('imagem_principal', models.ImageField(upload_to='pets_perdidos/', verbose_name='Foto Principal')),
                ('status', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('cancelado', 'Cancelado')], default='perdido', max_length=20, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Mapa')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_encontrado', models.DateTimeField(blank=True, null=True, verbose_name='Data que foi Encontrado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_perdidos', to='core.usuario', verbose_name='Dono do Pet')),
            ],
            options={
                'verbose_name': 'Pet Perdido',
                'verbose_name_plural': 'Pets Perdidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PetPerdidoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets_perdidos/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pet_perdido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionais', to='core.petperdido')),
            ],
            options={
                'verbose_name': 'Foto do Pet Perdido',
                'verbose_name_plural': 'Fotos do Pet Perdido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportePetEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100, verbose_name='Nome de Quem Encontrou')),
                ('telefone_contato', models.CharField(max_length=15, verbose_name='Telefone para Contato')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail para Contato')),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor/Pelagem')),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, verbose_name='Porte')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('N', 'Não sei informar')], default='N', max_length=1, verbose_name='Sexo')),
                ('descricao', models.TextField(help_text='Descreva as características físicas e comportamento', verbose_name='Descrição do Pet Encontrado')),
                ('caracteristicas_distintivas', models.TextField(blank=True, help_text='Coleira, manchas, cicatrizes, etc.', null=True, verbose_name='Características Distintivas')),
                ('data_encontro', models.DateField(verbose_name='Data que Encontrou')),
                ('hora_encontro', models.TimeField(blank=True, null=True, verbose_name='Hora Aproximada')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço onde Encontrou')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('pet_com_usuario', models.BooleanField(default=True, verbose_name='Pet está com você')),
                ('local_temporario', models.CharField(blank=True, help_text='Se o pet não está mais com você, onde ele está?', max_length=255, null=True, verbose_name='Local Temporário do Pet')),
                ('imagem_principal', models.ImageField(upload_to='pets_encontrados/', verbose_name='Foto Principal')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Análise'), ('aprovado', 'Match Confirmado'), ('rejeitado', 'Rejeitado'), ('em_analise', 'Em Análise')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes_admin', models.TextField(blank=True, null=True, verbose_name='Observações do Administrador')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Reporte')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('dono_notificado', models.BooleanField(default=False, verbose_name='Dono foi Notificado')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_analisados', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
                ('pet_perdido_confirmado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_confirmado', to='core.petperdido', verbose_name='Pet Perdido Confirmado')),
                ('possiveis_matches', models.ManyToManyField(blank=True, related_name='reportes_relacionados', to='core.petperdido', verbose_name='Possíveis Matches')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets_encontrados', to='core.usuario', verbose_name='Usuário que Encontrou')),
            ],
            options={
                'verbose_name': 'Reporte de Pet Encontrado',
                'verbose_name_plural': 'Reportes de Pets Encontrados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ReportePetEncontradoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets_encontrados/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionais', to='core.reportepetencontrado')),
            ],
            options={
                'verbose_name': 'Foto do Pet Encontrado',
                'verbose_name_plural': 'Fotos do Pet Encontrado',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='AnimalPerdido',
        ),
        migrations.AddIndex(
            model_name='petperdido',
            index=models.Index(fields=['status', 'ativo'], name='core_petper_status_3bfb12_idx'),
        ),
        migrations.AddIndex(
            model_name='petperdido',
            index=models.Index(fields=['cidade', 'estado'], name='core_petper_cidade_fd9e53_idx'),
        ),
        migrations.AddIndex(
            model_name='petperdido',
            index=models.Index(fields=['latitude', 'longitude'], name='core_petper_latitud_5febcd_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepetencontrado',
            index=models.Index(fields=['status'], name='core_report_status_3b99ac_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepetencontrado',
            index=models.Index(fields=['cidade', 'estado'], name='core_report_cidade_b6c473_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepetencontrado',
            index=models.Index(fields=['latitude', 'longitude'], name='core_report_latitud_f191ca_idx'),
        ),
    ]
