# Generated by Django 5.2.8 on 2025-11-22 03:50

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_petperdido_petperdidofoto_reportepetencontrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade onde o animal se encontra', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do animal (máximo 2000 caracteres)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[core.models.validar_estado_brasil]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_anos',
            field=models.IntegerField(blank=True, help_text='Idade em anos (0-30)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do animal (máximo 5MB)', null=True, upload_to='animais/', validators=[core.models.validar_tamanho_imagem, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Apenas imagens JPG, PNG ou WebP são permitidas')]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(help_text='Nome do animal (máximo 100 caracteres)', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, help_text='Raça do animal (opcional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='animalparaadocao',
            name='email',
            field=models.EmailField(help_text='E-mail válido para contato', max_length=254, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail para Contato'),
        ),
        migrations.AlterField(
            model_name='animalparaadocao',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text='Foto principal do animal (máximo 5MB)', null=True, upload_to='adocao/pendentes/', validators=[core.models.validar_tamanho_imagem, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Apenas imagens JPG, PNG ou WebP são permitidas')], verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='animalparaadocao',
            name='telefone',
            field=models.CharField(help_text='Formato: (11) 99999-9999', max_length=20, validators=[core.models.validar_telefone_brasileiro], verbose_name='Telefone para Contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(help_text='Assunto da mensagem (máximo 200 caracteres)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(help_text='E-mail válido para resposta', max_length=254, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')]),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(help_text='Mensagem detalhada (máximo 5000 caracteres)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(help_text='Nome completo (máximo 100 caracteres)', max_length=100),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(help_text='Descrição detalhada do caso (máximo 3000 caracteres)', max_length=3000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem principal (máximo 5MB)', null=True, upload_to='denuncias/', validators=[core.models.validar_tamanho_imagem, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Apenas imagens JPG, PNG ou WebP são permitidas')], verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(help_text='Endereço ou referência do local (máximo 255 caracteres)', max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='observacoes_moderador',
            field=models.TextField(blank=True, help_text='Observações internas da moderação (máximo 2000 caracteres)', max_length=2000, null=True, verbose_name='Observações do Moderador'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(help_text='Título resumido da denúncia (máximo 200 caracteres)', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo principal (máximo 20MB)', null=True, upload_to='denuncias/videos/', validators=[core.models.validar_tamanho_video, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'webm'], message='Apenas vídeos MP4, AVI, MOV, WMV ou WebM são permitidos')], verbose_name='Vídeo Principal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, help_text='Nome da cidade', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço completo (Rua, número, bairro)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla do estado (AC, SP, RJ, etc.)', max_length=2, null=True, validators=[core.models.validar_estado_brasil]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (11) 99999-9999', max_length=20, null=True, validators=[core.models.validar_telefone_brasileiro]),
        ),
    ]
