"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Diretórios
BASE_DIR = Path(__file__).resolve().parent.parent  # ...\backend\backend
SETTINGS_DIR = Path(__file__).resolve().parent     # ...\backend\backend\backend

# Carrega o .env que está AO LADO do settings.py
load_dotenv(SETTINGS_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3xbj62i8d=i&jy!6!xx(agod*lj@qk@ga)tkhc3p-79&*n96ws'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ajuste hosts para desenvolvimento
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'core',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Rate Limiting (Throttling)
    'DEFAULT_THROTTLE_CLASSES': [
        'core.throttling.AnonBurstRateThrottle',
        'core.throttling.AnonSustainedRateThrottle',
        'core.throttling.UserBurstRateThrottle',
        'core.throttling.UserSustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Limites gerais
        'anon_burst': '60/min',        # 60 requisições por minuto (burst)
        'anon_sustained': '1000/hour',  # 1000 requisições por hora (sustentado)
        'user_burst': '120/min',        # 120 requisições por minuto para logados
        'user_sustained': '5000/hour',  # 5000 requisições por hora para logados
        
        # Limites para ações específicas (mais restritivos)
        'registro': '5/hour',           # 5 registros por hora por IP
        'login': '10/hour',             # 10 tentativas de login por hora
        'contato': '5/hour',            # 5 mensagens de contato por hora
        'denuncia': '10/hour',          # 10 denúncias por hora
        'adocao': '5/hour',             # 5 solicitações de adoção por hora
        'pet_perdido': '10/hour',       # 10 cadastros de pet perdido por hora
        'upload': '20/hour',            # 20 uploads de arquivo por hora
        
        # Limites para leitura (mais permissivos)
        'list': '100/hour',             # 100 listagens por hora
        'detail': '200/hour',           # 200 visualizações de detalhes por hora
    },
}

# Configuração do drf-spectacular para evitar colisões de enums
SPECTACULAR_SETTINGS = {
    'TITLE': 'S.O.S Pets API',
    'DESCRIPTION': 'API para sistema de adoção e localização de pets',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_GENERATE_CHOICE_DESCRIPTION': False,
    'ENUM_NAME_OVERRIDES': {
        # Formato: 'ComponentPath': 'NomeDoEnum'
        # Resolve colisão do campo "sexo" 
        'AnimalSerializer.sexo': 'SexoAnimalEnum',
        'AnimalParaAdocaoSerializer.sexo': 'SexoPetAdocaoEnum',
        'PetPerdidoSerializer.sexo': 'SexoPetPerdidoEnum',
        'ReportePetEncontradoSerializer.sexo': 'SexoPetEncontradoEnum',
        # Resolve colisão do campo "porte"
        'AnimalSerializer.porte': 'PorteAnimalEnum',
        'AnimalParaAdocaoSerializer.porte': 'PortePetAdocaoEnum',
        'PetPerdidoSerializer.porte': 'PortePetPerdidoEnum',
        'ReportePetEncontradoSerializer.porte': 'PortePetEncontradoEnum',
    },
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '..' / '..' / 'TCC_SOS_Pets'],  # caminho para seu frontend (index.html)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'sos_pets'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# permitir que runserver sirva os arquivos estáticos do frontend durante dev
STATICFILES_DIRS = [BASE_DIR / '..' / '..' / 'TCC_SOS_Pets']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# adicionar no final do arquivo ou onde preferir
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Dentro do diretório do app no Docker

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

CORS_ALLOW_CREDENTIALS = True

# CSRF Configuration for API
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Logging Configuration - Suprime warnings específicos de enum do drf-spectacular
import warnings
warnings.filterwarnings(
    'ignore',
    message='.*enum naming encountered a non-optimally resolvable collision.*',
    category=UserWarning,
    module='drf_spectacular.openapi'
)
